base:
  project: Thyroid_detection-project
  random_state: 355
  target_col: Class

data_source:
  training_source: Training_Batch_Files
  null_dir: data/null_data/null_data.csv
  balanced_sampled_data: data/after_handling_imbalance/sample_data.csv

load_data:
  good_data_csv: data/processed/good_data.csv

split_data:
  train_path: data/processed/train_data.csv
  test_path: data/processed/test_data.csv
  test_size: 0.2

estimators:
  XGBClassifier:
    params:
      max_depth: 6
      learning_rate: 0.300000012
      n_estimators: 100
      n_jobs: 4

reports:
  params: reports/params.json
  scores: reports/scores.json

model_dir: saved_models
